module.exports = {
    session:{
      sessionId:String,
      content:String,
      createTime:Date,
      updateTime:Date
    },
    message:{
        type:String,
        itemType:String,
        data:String,
        channel:String,//渠道
        ip:String,//IP
        status:String,
        content:String,
        remark:String,
        userId:String,
        createTime:Date,
        updateTime:Date
    },
    sms:{
        phone:String,//手机号
        channel:String,//渠道
        sendType:String,//短信类型
        userId:String,//用户id
        ip:String,//IP
        date:String,//日期
        code:String,//验证码
        checkCount:Number,//校验次数
        check:Boolean,//是否验证通过
        createTime:Date,
        updateTime:Date
    },
    operator:{
        company:String,
        companyName:String,
        username:String,
        nickname:String,
        uid:String,
        password:String,
        type:Number,
        status:Number,//0修改密码 1正常 2锁定
        roleId:Array,
        createOperator:String,
        createTime:Date,
        updateTime:Date
    },
    permission:{//单个权限
        type:Number,//0内部 1商户
        name:String,
        code:String,
        menuCode:String,
        createTime:Date,
        updateTime:Date,
    },
    permissionRelation:{//角色
        company:String,
        name:String,
        permissionCode:Array,
        menuCode:Array,
        groupId:Array,
        createOperator:String,
        createTime:Date,
        updateTime:Date,
    },
    permissionMenu:{//菜单权限
        type:Number,//0内部 1商户
        name:String,
        code:String,
        parentCode:String,
        createTime:Date,
        updateTime:Date,
        isAdmin:Boolean
    },
    channelConfig:{
        company:String,
        createTime:Date,
        updateTime:Date,
    },
    merchantSettle:{
        name:String,
        tel:String,
        address:String,
        email:String,
        remark:String,
        status:Number,
        createTime:Date,
        updateTime:Date,
    },
    merchantCart:{
        merchantId:String,
        chatRoomId:String,
        chatRoomName:String,
        createTime:Date,
        updateTime:Date,
    },
};
